/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'city' : string,
  'zipCode' : string,
}
export type Category = { 'streetlights' : null } |
  { 'other' : null } |
  { 'potholes' : null } |
  { 'waste' : null };
export interface Comment {
  'id' : string,
  'content' : string,
  'userId' : Principal,
  'timestamp' : Time,
  'submissionId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GeoCoordinates { 'latitude' : number, 'longitude' : number }
export interface LoginError { 'code' : LoginErrorCode, 'message' : string }
export type LoginErrorCode = { 'internalError' : null } |
  { 'unauthorized' : null } |
  { 'invalidCredentials' : null };
export type LoginResult = { 'error' : LoginError } |
  { 'success' : LoginSuccess };
export interface LoginSuccess {
  'redirectView' : string,
  'isAuthenticated' : boolean,
  'isMunicipalOperator' : boolean,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Status = { 'reopened' : null } |
  { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface StatusUpdate {
  'updatedBy' : Principal,
  'notes' : string,
  'timestamp' : Time,
  'submissionId' : string,
  'newStatus' : Status,
  'previousStatus' : Status,
}
export interface Submission {
  'id' : string,
  'status' : Status,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'updatedAt' : Time,
  'address' : [] | [Address],
  'assignedStaff' : [] | [Principal],
  'category' : Category,
  'priority' : Priority,
  'location' : [] | [GeoCoordinates],
  'attachments' : Array<ExternalBlob>,
}
export type Time = bigint;
export interface UserProfile {
  'isMunicipalStaff' : boolean,
  'name' : string,
  'email' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, string], undefined>,
  'addVote' : ActorMethod<
    [string, { 'upvote' : null } | { 'downvote' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSubmissionToStaff' : ActorMethod<
    [string, [] | [Principal]],
    undefined
  >,
  'createSubmission' : ActorMethod<[Submission], string>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deleteSubmission' : ActorMethod<[string], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'closedSubmissions' : bigint,
      'inProgressSubmissions' : bigint,
      'totalSubmissions' : bigint,
      'resolvedSubmissions' : bigint,
      'openSubmissions' : bigint,
    }
  >,
  'getAssignedSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getMySubmissions' : ActorMethod<[], Array<Submission>>,
  'getStatusHistory' : ActorMethod<[string], Array<StatusUpdate>>,
  'getSubmission' : ActorMethod<[string], Submission>,
  'getSubmissionByCategory' : ActorMethod<[Category], Array<Submission>>,
  'getSubmissionVersions' : ActorMethod<[string], Array<string>>,
  'getSubmissionsByStatus' : ActorMethod<[Status], Array<Submission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteCount' : ActorMethod<
    [string],
    { 'upvotes' : bigint, 'downvotes' : bigint }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[boolean], LoginResult>,
  'removeVote' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMunicipalStaffStatus' : ActorMethod<[Principal, boolean], undefined>,
  'updateSubmission' : ActorMethod<[string, Submission], undefined>,
  'updateSubmissionStatus' : ActorMethod<[string, Status, string], undefined>,
  'uploadAttachment' : ActorMethod<[string, Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];