/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Comment {
    id: string;
    content: string;
    userId: Principal;
    timestamp: Time;
    submissionId: string;
}
export interface LoginSuccess {
    redirectView: string;
    isAuthenticated: boolean;
    isMunicipalOperator: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface GeoCoordinates {
    latitude: number;
    longitude: number;
}
export interface Address {
    street: string;
    city: string;
    zipCode: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface StatusUpdate {
    updatedBy: Principal;
    notes: string;
    timestamp: Time;
    submissionId: string;
    newStatus: Status;
    previousStatus: Status;
}
export interface LoginError {
    code: LoginErrorCode;
    message: string;
}
export type LoginResult = {
    __kind__: "error";
    error: LoginError;
} | {
    __kind__: "success";
    success: LoginSuccess;
};
export interface Submission {
    id: string;
    status: Status;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    updatedAt: Time;
    address?: Address;
    assignedStaff?: Principal;
    category: Category;
    priority: Priority;
    location?: GeoCoordinates;
    attachments: Array<ExternalBlob>;
}
export interface UserProfile {
    isMunicipalStaff: boolean;
    name: string;
    email: string;
    phone?: string;
}
export enum Category {
    garbage = "garbage",
    traffic = "traffic",
    potholes = "potholes",
    noise = "noise",
    streetlight = "streetlight"
}
export enum LoginErrorCode {
    internalError = "internalError",
    unauthorized = "unauthorized",
    invalidCredentials = "invalidCredentials"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    resolved = "resolved",
    pending = "pending",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_upvote_downvote {
    upvote = "upvote",
    downvote = "downvote"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(submissionId: string, content: string, commentId: string): Promise<void>;
    addVote(submissionId: string, voteType: Variant_upvote_downvote): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignSubmissionToStaff(id: string, staffPrincipal: Principal | null): Promise<void>;
    createSubmission(payload: Submission): Promise<string>;
    deleteComment(commentId: string): Promise<void>;
    deleteSubmission(id: string): Promise<void>;
    getAllSubmissions(): Promise<Array<Submission>>;
    getAnalytics(): Promise<{
        pendingSubmissions: bigint;
        inProgressSubmissions: bigint;
        totalSubmissions: bigint;
        resolvedSubmissions: bigint;
    }>;
    getAssignedSubmissions(): Promise<Array<Submission>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(submissionId: string): Promise<Array<Comment>>;
    getMySubmissions(): Promise<Array<Submission>>;
    getStatusHistory(submissionId: string): Promise<Array<StatusUpdate>>;
    getSubmission(id: string): Promise<Submission>;
    getSubmissionByCategory(category: Category): Promise<Array<Submission>>;
    getSubmissionVersions(id: string): Promise<Array<string>>;
    getSubmissionsByStatus(status: Status): Promise<Array<Submission>>;
    getSubmissionsByUser(userId: Principal): Promise<Array<Submission>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoteCount(submissionId: string): Promise<{
        upvotes: bigint;
        downvotes: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    login(): Promise<LoginResult>;
    removeVote(submissionId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    setMunicipalStaffStatus(user: Principal, isStaff: boolean): Promise<void>;
    updateSubmission(id: string, newPayload: Submission): Promise<void>;
    updateSubmissionStatus(id: string, newStatus: Status, notes: string): Promise<void>;
    uploadAttachment(submissionId: string, blobs: Array<ExternalBlob>): Promise<void>;
}
import type { Address as _Address, Category as _Category, ExternalBlob as _ExternalBlob, GeoCoordinates as _GeoCoordinates, LoginError as _LoginError, LoginErrorCode as _LoginErrorCode, LoginResult as _LoginResult, LoginSuccess as _LoginSuccess, Priority as _Priority, Status as _Status, StatusUpdate as _StatusUpdate, Submission as _Submission, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async addVote(arg0: string, arg1: Variant_upvote_downvote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVote(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVote(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignSubmissionToStaff(arg0: string, arg1: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSubmissionToStaff(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSubmissionToStaff(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSubmission(arg0: Submission): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubmission(await to_candid_Submission_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubmission(await to_candid_Submission_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<{
        pendingSubmissions: bigint;
        inProgressSubmissions: bigint;
        totalSubmissions: bigint;
        resolvedSubmissions: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getAssignedSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedSubmissions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedSubmissions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getMySubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatusHistory(arg0: string): Promise<Array<StatusUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusHistory(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusHistory(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<Submission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_Submission_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_Submission_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionByCategory(arg0: Category): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionByCategory(to_candid_Category_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionByCategory(to_candid_Category_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionVersions(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionVersions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionVersions(arg0);
            return result;
        }
    }
    async getSubmissionsByStatus(arg0: Status): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByStatus(to_candid_Status_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByStatus(to_candid_Status_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByUser(arg0: Principal): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByUser(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByUser(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoteCount(arg0: string): Promise<{
        upvotes: bigint;
        downvotes: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login();
                return from_candid_LoginResult_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login();
            return from_candid_LoginResult_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeVote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVote(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async setMunicipalStaffStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMunicipalStaffStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMunicipalStaffStatus(arg0, arg1);
            return result;
        }
    }
    async updateSubmission(arg0: string, arg1: Submission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmission(arg0, await to_candid_Submission_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmission(arg0, await to_candid_Submission_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubmissionStatus(arg0: string, arg1: Status, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, to_candid_Status_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async uploadAttachment(arg0: string, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAttachment(arg0, await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAttachment(arg0, await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LoginErrorCode_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginErrorCode): LoginErrorCode {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_LoginError_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginError): LoginError {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_StatusUpdate_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusUpdate): StatusUpdate {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Submission_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Promise<Submission> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Address]): Address | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoCoordinates]): GeoCoordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    title: string;
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    updatedAt: _Time;
    address: [] | [_Address];
    assignedStaff: [] | [Principal];
    category: _Category;
    priority: _Priority;
    location: [] | [_GeoCoordinates];
    attachments: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    status: Status;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    updatedAt: Time;
    address?: Address;
    assignedStaff?: Principal;
    category: Category;
    priority: Priority;
    location?: GeoCoordinates;
    attachments: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        updatedAt: value.updatedAt,
        address: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.address)),
        assignedStaff: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.assignedStaff)),
        category: from_candid_Category_n29(_uploadFile, _downloadFile, value.category),
        priority: from_candid_Priority_n31(_uploadFile, _downloadFile, value.priority),
        location: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.location)),
        attachments: await from_candid_vec_n34(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMunicipalStaff: boolean;
    name: string;
    email: string;
    phone: [] | [string];
}): {
    isMunicipalStaff: boolean;
    name: string;
    email: string;
    phone?: string;
} {
    return {
        isMunicipalStaff: value.isMunicipalStaff,
        name: value.name,
        email: value.email,
        phone: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    updatedBy: Principal;
    notes: string;
    timestamp: _Time;
    submissionId: string;
    newStatus: _Status;
    previousStatus: _Status;
}): {
    updatedBy: Principal;
    notes: string;
    timestamp: Time;
    submissionId: string;
    newStatus: Status;
    previousStatus: Status;
} {
    return {
        updatedBy: value.updatedBy,
        notes: value.notes,
        timestamp: value.timestamp,
        submissionId: value.submissionId,
        newStatus: from_candid_Status_n25(_uploadFile, _downloadFile, value.newStatus),
        previousStatus: from_candid_Status_n25(_uploadFile, _downloadFile, value.previousStatus)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: _LoginErrorCode;
    message: string;
}): {
    code: LoginErrorCode;
    message: string;
} {
    return {
        code: from_candid_LoginErrorCode_n49(_uploadFile, _downloadFile, value.code),
        message: value.message
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    inProgress: null;
}): Status {
    return "resolved" in value ? Status.resolved : "pending" in value ? Status.pending : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    garbage: null;
} | {
    traffic: null;
} | {
    potholes: null;
} | {
    noise: null;
} | {
    streetlight: null;
}): Category {
    return "garbage" in value ? Category.garbage : "traffic" in value ? Category.traffic : "potholes" in value ? Category.potholes : "noise" in value ? Category.noise : "streetlight" in value ? Category.streetlight : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: _LoginError;
} | {
    success: _LoginSuccess;
}): {
    __kind__: "error";
    error: LoginError;
} | {
    __kind__: "success";
    success: LoginSuccess;
} {
    return "error" in value ? {
        __kind__: "error",
        error: from_candid_LoginError_n47(_uploadFile, _downloadFile, value.error)
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internalError: null;
} | {
    unauthorized: null;
} | {
    invalidCredentials: null;
}): LoginErrorCode {
    return "internalError" in value ? LoginErrorCode.internalError : "unauthorized" in value ? LoginErrorCode.unauthorized : "invalidCredentials" in value ? LoginErrorCode.invalidCredentials : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Promise<Array<Submission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Submission_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusUpdate>): Array<StatusUpdate> {
    return value.map((x)=>from_candid_StatusUpdate_n43(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Priority_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Submission_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Submission): Promise<_Submission> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    updatedAt: Time;
    address?: Address;
    assignedStaff?: Principal;
    category: Category;
    priority: Priority;
    location?: GeoCoordinates;
    attachments: Array<ExternalBlob>;
}): Promise<{
    id: string;
    status: _Status;
    title: string;
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    updatedAt: _Time;
    address: [] | [_Address];
    assignedStaff: [] | [Principal];
    category: _Category;
    priority: _Priority;
    location: [] | [_GeoCoordinates];
    attachments: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        status: to_candid_Status_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        updatedAt: value.updatedAt,
        address: value.address ? candid_some(value.address) : candid_none(),
        assignedStaff: value.assignedStaff ? candid_some(value.assignedStaff) : candid_none(),
        category: to_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        priority: to_candid_Priority_n18(_uploadFile, _downloadFile, value.priority),
        location: value.location ? candid_some(value.location) : candid_none(),
        attachments: await to_candid_vec_n20(_uploadFile, _downloadFile, value.attachments)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMunicipalStaff: boolean;
    name: string;
    email: string;
    phone?: string;
}): {
    isMunicipalStaff: boolean;
    name: string;
    email: string;
    phone: [] | [string];
} {
    return {
        isMunicipalStaff: value.isMunicipalStaff,
        name: value.name,
        email: value.email,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    resolved: null;
} | {
    pending: null;
} | {
    inProgress: null;
} {
    return value == Status.resolved ? {
        resolved: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    garbage: null;
} | {
    traffic: null;
} | {
    potholes: null;
} | {
    noise: null;
} | {
    streetlight: null;
} {
    return value == Category.garbage ? {
        garbage: null
    } : value == Category.traffic ? {
        traffic: null
    } : value == Category.potholes ? {
        potholes: null
    } : value == Category.noise ? {
        noise: null
    } : value == Category.streetlight ? {
        streetlight: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upvote_downvote): {
    upvote: null;
} | {
    downvote: null;
} {
    return value == Variant_upvote_downvote.upvote ? {
        upvote: null
    } : value == Variant_upvote_downvote.downvote ? {
        downvote: null
    } : value;
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
