/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'reopened' : IDL.Null,
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const Address = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
});
export const Category = IDL.Variant({
  'streetlights' : IDL.Null,
  'other' : IDL.Null,
  'potholes' : IDL.Null,
  'waste' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const GeoCoordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Submission = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Opt(Address),
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'category' : Category,
  'priority' : Priority,
  'location' : IDL.Opt(GeoCoordinates),
  'attachments' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'isMunicipalStaff' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'submissionId' : IDL.Text,
});
export const StatusUpdate = IDL.Record({
  'updatedBy' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'submissionId' : IDL.Text,
  'newStatus' : Status,
  'previousStatus' : Status,
});
export const LoginErrorCode = IDL.Variant({
  'internalError' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const LoginError = IDL.Record({
  'code' : LoginErrorCode,
  'message' : IDL.Text,
});
export const LoginSuccess = IDL.Record({
  'redirectView' : IDL.Text,
  'isAuthenticated' : IDL.Bool,
  'isMunicipalOperator' : IDL.Bool,
});
export const LoginResult = IDL.Variant({
  'error' : LoginError,
  'success' : LoginSuccess,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addVote' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'upvote' : IDL.Null, 'downvote' : IDL.Null })],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSubmissionToStaff' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'createSubmission' : IDL.Func([Submission], [IDL.Text], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deleteSubmission' : IDL.Func([IDL.Text], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'closedSubmissions' : IDL.Nat,
          'inProgressSubmissions' : IDL.Nat,
          'totalSubmissions' : IDL.Nat,
          'resolvedSubmissions' : IDL.Nat,
          'openSubmissions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAssignedSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getStatusHistory' : IDL.Func([IDL.Text], [IDL.Vec(StatusUpdate)], ['query']),
  'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
  'getSubmissionByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getSubmissionVersions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSubmissionsByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getSubmissionsSortedByUpvotes' : IDL.Func(
      [],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteCount' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'upvotes' : IDL.Nat, 'downvotes' : IDL.Nat })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Bool], [LoginResult], []),
  'removeVote' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMunicipalStaffStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateSubmission' : IDL.Func([IDL.Text, Submission], [], []),
  'updateSubmissionStatus' : IDL.Func([IDL.Text, Status, IDL.Text], [], []),
  'uploadAttachment' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'reopened' : IDL.Null,
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const Address = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
  });
  const Category = IDL.Variant({
    'streetlights' : IDL.Null,
    'other' : IDL.Null,
    'potholes' : IDL.Null,
    'waste' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const GeoCoordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Submission = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Opt(Address),
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'category' : Category,
    'priority' : Priority,
    'location' : IDL.Opt(GeoCoordinates),
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'isMunicipalStaff' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'submissionId' : IDL.Text,
  });
  const StatusUpdate = IDL.Record({
    'updatedBy' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'submissionId' : IDL.Text,
    'newStatus' : Status,
    'previousStatus' : Status,
  });
  const LoginErrorCode = IDL.Variant({
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const LoginError = IDL.Record({
    'code' : LoginErrorCode,
    'message' : IDL.Text,
  });
  const LoginSuccess = IDL.Record({
    'redirectView' : IDL.Text,
    'isAuthenticated' : IDL.Bool,
    'isMunicipalOperator' : IDL.Bool,
  });
  const LoginResult = IDL.Variant({
    'error' : LoginError,
    'success' : LoginSuccess,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addVote' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'upvote' : IDL.Null, 'downvote' : IDL.Null })],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSubmissionToStaff' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'createSubmission' : IDL.Func([Submission], [IDL.Text], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deleteSubmission' : IDL.Func([IDL.Text], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'closedSubmissions' : IDL.Nat,
            'inProgressSubmissions' : IDL.Nat,
            'totalSubmissions' : IDL.Nat,
            'resolvedSubmissions' : IDL.Nat,
            'openSubmissions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAssignedSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getStatusHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StatusUpdate)],
        ['query'],
      ),
    'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
    'getSubmissionByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getSubmissionVersions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSubmissionsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getSubmissionsSortedByUpvotes' : IDL.Func(
        [],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteCount' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'upvotes' : IDL.Nat, 'downvotes' : IDL.Nat })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Bool], [LoginResult], []),
    'removeVote' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMunicipalStaffStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateSubmission' : IDL.Func([IDL.Text, Submission], [], []),
    'updateSubmissionStatus' : IDL.Func([IDL.Text, Status, IDL.Text], [], []),
    'uploadAttachment' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };